# Generated by Django 5.2.7 on 2025-11-27 20:58

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Main headline text')),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or Bible verse reference', max_length=200)),
                ('description', models.TextField(help_text='Quote or descriptive text')),
                ('bible_verse', models.TextField(blank=True, help_text='Full Bible verse text')),
                ('button_text', models.CharField(default='Read Full Devotion', max_length=50)),
                ('button_link', models.URLField(default='https://whiteestate.org/devotional/mlt/')),
                ('background_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hero/')),
                ('active', models.BooleanField(default=True, help_text='Whether this hero section is currently active')),
                ('order', models.IntegerField(default=0, help_text='Display order if multiple hero sections exist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
